# Generated by Django 4.2.16 on 2024-11-06 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('photos', models.ImageField(blank=True, null=True, upload_to='recommend/tour_images', verbose_name='관광지 이미지')),
            ],
            options={
                'unique_together': {('visit_name', 'address')},
            },
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('travel_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('travel_name', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('movement_name', models.CharField(blank=True, max_length=100)),
                ('companion_num', models.PositiveIntegerField(default=0)),
                ('relationship', models.TextField(blank=True, null=True)),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('visits', models.ManyToManyField(to='recommend.visit')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommend.visit')),
            ],
        ),
        migrations.CreateModel(
            name='PopularTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_count', models.PositiveIntegerField(default=0)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommend.visit')),
            ],
        ),
        migrations.CreateModel(
            name='Consume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('transportation', '이동수단'), ('lodging', '숙박'), ('advance', '사전 소비'), ('activity', '활동')], max_length=20)),
                ('consume_name', models.CharField(blank=True, max_length=100)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('details', models.TextField(blank=True, null=True, verbose_name='세부 내용')),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommend.travel')),
            ],
        ),
    ]
