# Generated by Django 4.2.16 on 2024-11-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TouristSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('touristspot_name', models.CharField(max_length=50)),
                ('main_cate', models.CharField(max_length=50)),
                ('second_cate', models.CharField(max_length=50)),
                ('third_cate', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('tags', models.JSONField(blank=True, null=True)),
                ('tags_text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
